const SUPABASE_URL='https://ewhoumxgaiigfcysrciw.supabase.co';
const SUPABASE_KEY='sb_publishable_AbWbVq8AJCGijBANXM6ESw_6mkATylt';
const db=supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const SESSION_KEY='actress-tcg-session';
let session=JSON.parse(localStorage.getItem(SESSION_KEY)||'null');
let cards=[];
let collection=[];
let leaderboardRows=[];
function esc(x){return String(x??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function setSession(x){session=x;localStorage.setItem(SESSION_KEY,JSON.stringify(x))}
function clearSession(){session=null;localStorage.removeItem(SESSION_KEY)}
function errorText(e){return e?.message||'Something went wrong.'}
function cd(){if(!session?.player?.last_pack_batch_at)return 0;return Math.max(0,3600000-(Date.now()-new Date(session.player.last_pack_batch_at).getTime()))}
function time(ms){let q=Math.ceil(ms/1000),h=Math.floor(q/3600),m=Math.floor(q%3600/60),s=q%60;return h?h+'h '+m+'m':m?m+'m '+s+'s':s+'s'}
async function loadCards(){const {data,error}=await db.rpc('get_cards');if(!error)cards=data||[]}
async function loadCollection(){if(!session)return;const {data,error}=await db.rpc('get_collection',{p_player_id:session.player.id,p_session_token:session.token});if(!error)collection=data||[]}
async function loadLeaderboard(){const {data,error}=await db.rpc('get_leaderboard');if(!error)leaderboardRows=data||[]}
function login(){document.getElementById('app').innerHTML='<div class="shell"><div class="login"><section class="hero"><div class="brand">ACTRESS <span>TCG</span></div><h1>Collect the stars.</h1><p>Open three cards every hour, build your collection and inspect every card.</p></section><form class="form" onsubmit="event.preventDefault();enter()"><input class="input" id="u" placeholder="Username" required><input class="input" id="p" type="password" placeholder="Password" required><button class="btn primary">Enter TCG</button></form><div id="msg"></div><p class="muted">Admin: 6102000 / 6102000</p></div></div>'}
async function enter(){const u=document.getElementById('u').value.trim(),p=document.getElementById('p').value,box=document.getElementById('msg');box.innerHTML='<div class="notice">Connecting...</div>';let {data,error}=await db.rpc('login_player',{p_username:u,p_password:p});if(error||!data?.success){if(!data?.success&&u!=='6102000'){const r=await db.rpc('register_player',{p_username:u,p_password:p,p_display_name:u});if(!r.error&&r.data?.success)data=r.data;else{box.innerHTML='<div class="notice">'+esc(r.data?.error||errorText(error))+'</div>';return}}else{box.innerHTML='<div class="notice">'+esc(data?.error||errorText(error))+'</div>';return}}setSession(data);await start()}
async function start(){await loadCards();await loadCollection();render()}
async function logout(){if(session?.token)await db.rpc('logout_player',{p_token:session.token});clearSession();login()}
function nav(){return '<header class="top"><div class="brand">ACTRESS <span>TCG</span></div><nav class="nav"><button class="btn" onclick="home()">Home</button><button class="btn" onclick="collectionPage()">Collection</button><button class="btn" onclick="leaderboardPage()">Leaderboard</button>'+(session.player.role==='ADMIN'?'<button class="btn gold" onclick="admin()">Admin</button>':'')+'<button class="btn" onclick="logout()">Logout</button></nav></header>'}
function render(){if(!session){login();return}document.getElementById('app').innerHTML='<div class="shell">'+nav()+'<main id="main"></main><div class="footer">3 cards per pack • 1 hour cooldown • Supabase connected</div></div>';home()}
function card(c,copies){return '<article class="card" onclick="showCard(\''+c.id+'\')"><img class="photo" src="'+esc(c.photo_url||'https://placehold.co/600x800/32121a/ffffff?text=Actress')+'" alt="'+esc(c.name)+'"><div class="cardbody"><div class="rarity">'+esc(c.rarity)+'</div><h3>'+esc(c.name)+'</h3><div class="small">Age '+(c.age??'—')+' • '+esc(c.date_of_birth||'—')+'</div>'+(copies?'<span class="pill">Owned ×'+copies+'</span>':'')+'</div></article>'}
function total(){return collection.reduce((a,x)=>a+x.copies,0)}
function home(){let wait=cd();document.getElementById('main').innerHTML='<section class="hero"><h1>Collect the stars.</h1><p>Open exactly three cards. All three cards open together, then a one-hour cooldown starts.</p><div class="stats"><div class="stat"><b>'+total()+'</b><span class="small">Cards owned</span></div><div class="stat"><b>'+collection.length+'</b><span class="small">Unique cards</span></div><div class="stat"><b>'+cards.length+'</b><span class="small">Catalog cards</span></div></div><button class="btn primary" '+(wait?'disabled':'')+' onclick="openPack()">'+(wait?'Next pack in '+time(wait):'Open 3-card pack')+'</button></section><section><h2>Card catalog</h2><div class="cards">'+cards.map(c=>card(c,collection.find(x=>x.card.id===c.id)?.copies||0)).join('')+'</div></section>';if(wait)setTimeout(home,1000)}
async function openPack(){if(cd())return;const btn=document.querySelector('.hero .btn');if(btn)btn.disabled=true;const {data,error}=await db.rpc('open_pack',{p_player_id:session.player.id,p_pack_type:'STANDARD',p_session_token:session.token});if(error){alert(errorText(error));return}session.player.last_pack_batch_at=new Date().toISOString();setSession(session);const got=data.cards||[];await loadCollection();document.getElementById('main').innerHTML='<section class="hero"><h1>Pack opened!</h1><p>All three cards were opened together and added to your collection.</p><div class="cards">'+got.map(c=>card(c,collection.find(x=>x.card.id===c.id)?.copies||1)).join('')+'</div><br><button class="btn" onclick="collectionPage()">View collection</button></section>'}
async function collectionPage(){await loadCollection();const a=collection;document.getElementById('main').innerHTML='<section class="hero"><h1>My Collection</h1><p>'+a.length+' unique cards • '+total()+' total copies</p></section>'+(a.length?'<div class="cards">'+a.map(x=>card(x.card,x.copies)).join('')+'</div>':'<div class="empty">No cards yet. Open your first pack.</div>')}
async function leaderboardPage(){await loadLeaderboard();document.getElementById('main').innerHTML='<section class="hero"><h1>Leaderboard</h1><p>Shared between all players through Supabase.</p></section><table class="table"><tr><th>#</th><th>Username</th><th>Total</th><th>Unique</th></tr>'+leaderboardRows.map((x,i)=>'<tr><td>'+(i+1)+'</td><td>'+esc(x.username)+'</td><td>'+x.total_cards+'</td><td>'+x.unique_cards+'</td></tr>').join('')+'</table>'}
function showCard(id){const c=cards.find(x=>x.id===id);if(!c)return;const own=collection.find(x=>x.card.id===id)?.copies||0;const movies=Array.isArray(c.movies)?c.movies:[];document.body.insertAdjacentHTML('beforeend','<div class="modal" id="modal" onclick="if(event.target.id===\'modal\')closeModal()"><div class="dialog"><button class="btn close" onclick="closeModal()">Close</button><div class="detail"><img src="'+esc(c.photo_url||'https://placehold.co/600x800')+'"><div><div class="rarity">'+esc(c.rarity)+'</div><h1>'+esc(c.name)+'</h1><p class="muted">Age: '+(c.age??'—')+'<br>Date of birth: '+esc(c.date_of_birth||'—')+'</p><h3>Movies</h3><p>'+movies.map(esc).join(' • ')+'</p><p>'+esc(c.description||'')+'</p><span class="pill">Owned ×'+own+'</span></div></div></div></div>')}
function closeModal(){document.getElementById('modal')?.remove()}
function admin(){if(session.player.role!=='ADMIN')return;document.getElementById('main').innerHTML='<section class="hero"><h1>Admin</h1><p>Create a new card and upload its photo to Supabase.</p></section><form class="form" onsubmit="event.preventDefault();addCard()"><input class="input" id="n" placeholder="Actress name" required><input class="input" id="ph" type="file" accept="image/*" required><input class="input" id="ag" type="number" placeholder="Age" required><input class="input" id="dob" type="date"><input class="input" id="mv" placeholder="Movie names, comma separated"><select class="input" id="ra"><option>Common</option><option>Rare</option><option>Epic</option><option>Legendary</option></select><input class="input" id="de" placeholder="Description"><button class="btn primary">Upload Photo & Create Card</button></form>'}
async function addCard(){const file=document.getElementById('ph').files[0];if(!file){alert('Choose a photo.');return}const path=crypto.randomUUID()+'-'+file.name.replace(/[^a-zA-Z0-9._-]/g,'_');const up=await db.storage.from('card-photos').upload(path,file,{contentType:file.type,upsert:false});if(up.error){alert(up.error.message);return}const url=db.storage.from('card-photos').getPublicUrl(path).data.publicUrl;const movies=document.getElementById('mv').value.split(',').map(x=>x.trim()).filter(Boolean);const r=await db.rpc('admin_create_card',{p_session_token:session.token,p_name:document.getElementById('n').value,p_age:Number(document.getElementById('ag').value)||null,p_dob:document.getElementById('dob').value||null,p_movies:movies,p_photo_url:url,p_rarity:document.getElementById('ra').value,p_description:document.getElementById('de').value||'Actress TCG card.'});if(r.error){alert(r.error.message);return}await loadCards();alert('Card created successfully.');admin()}
start();