const K='actress-tcg-v2';
const seed=[
{id:1,name:'Demo Actress One',age:28,dob:'1998-01-14',movies:['First Light','Red Summer'],rarity:'Rare',photo:'https://placehold.co/600x800/4a1520/ffffff?text=Actress+One',desc:'A starter collection card.'},
{id:2,name:'Demo Actress Two',age:31,dob:'1995-05-22',movies:['Moon City','The Last Scene'],rarity:'Epic',photo:'https://placehold.co/600x800/26104a/ffffff?text=Actress+Two',desc:'An epic demo card.'},
{id:3,name:'Demo Actress Three',age:25,dob:'2001-09-03',movies:['Golden Hour','Velvet Road'],rarity:'Legendary',photo:'https://placehold.co/600x800/6a4210/ffffff?text=Actress+Three',desc:'A legendary demo card.'},
{id:4,name:'Demo Actress Four',age:34,dob:'1992-02-10',movies:['North Star'],rarity:'Common',photo:'https://placehold.co/600x800/263238/ffffff?text=Actress+Four',desc:'A common demo card.'},
{id:5,name:'Demo Actress Five',age:29,dob:'1997-07-19',movies:['After Rain'],rarity:'Rare',photo:'https://placehold.co/600x800/3b1740/ffffff?text=Actress+Five',desc:'A rare demo card.'},
{id:6,name:'Demo Actress Six',age:27,dob:'1999-11-30',movies:['Neon Nights'],rarity:'Epic',photo:'https://placehold.co/600x800/163b4a/ffffff?text=Actress+Six',desc:'An epic demo card.'}];
let s=load();
function load(){try{return Object.assign({user:null,users:{},cards:seed,collection:{},lastPack:0},JSON.parse(localStorage.getItem(K)||'{}'))}catch(e){return {user:null,users:{},cards:seed,collection:{},lastPack:0}}}
function save(){localStorage.setItem(K,JSON.stringify(s))}
function esc(x){return String(x||'').replace(/[&<>"']/g,function(m){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]})}
function mine(){return s.collection[s.user]||{}}
function total(){return Object.values(mine()).reduce(function(a,b){return a+b},0)}
function cd(){return Math.max(0,3600000-(Date.now()-s.lastPack))}
function time(ms){var q=Math.ceil(ms/1000),h=Math.floor(q/3600),m=Math.floor(q%3600/60),z=q%60;return h?h+'h '+m+'m':m?m+'m '+z+'s':z+'s'}
function login(){document.getElementById('app').innerHTML='<div class="shell"><div class="login"><section class="hero"><div class="brand">ACTRESS <span>TCG</span></div><h1>Collect the stars.</h1><p>Open three cards every hour, build your collection and inspect every card.</p></section><form class="form" onsubmit="event.preventDefault();enter()"><input class="input" id="u" placeholder="Username" required><input class="input" id="p" type="password" placeholder="Password" required><button class="btn primary">Enter TCG</button></form><div id="msg"></div><p class="muted">Admin demo: 6102000 / 6102000</p></div></div>'}
function enter(){var u=document.getElementById('u').value.trim(),p=document.getElementById('p').value;if(u==='6102000'&&p==='6102000'){s.user=u;s.users[u]={password:p};save();render();return}if(s.users[u]&&s.users[u].password!==p){document.getElementById('msg').innerHTML='<div class="notice">Incorrect password.</div>';return}s.users[u]={password:p};s.user=u;save();render()}
function logout(){s.user=null;save();login()}
function nav(){return '<header class="top"><div class="brand">ACTRESS <span>TCG</span></div><nav class="nav"><button class="btn" onclick="home()">Home</button><button class="btn" onclick="collection()">Collection</button><button class="btn" onclick="leaderboard()">Leaderboard</button>'+(s.user==='6102000'?'<button class="btn gold" onclick="admin()">Admin</button>':'')+'<button class="btn" onclick="logout()">Logout</button></nav></header>'}
function render(){if(!s.user){login();return}document.getElementById('app').innerHTML='<div class="shell">'+nav()+'<main id="main"></main><div class="footer">3 cards per pack • 1 hour cooldown • browser-only storage</div></div>';home()}
function card(c){var n=mine()[c.id]||0;return '<article class="card" onclick="showCard('+c.id+')"><img class="photo" src="'+esc(c.photo)+'" alt="'+esc(c.name)+'"><div class="cardbody"><div class="rarity">'+esc(c.rarity)+'</div><h3>'+esc(c.name)+'</h3><div class="small">Age '+c.age+' • '+esc(c.dob)+'</div>'+(n?'<span class="pill">Owned ×'+n+'</span>':'')+'</div></article>'}
function home(){var wait=cd(),button=wait?'Next pack in '+time(wait):'Open 3-card pack';document.getElementById('main').innerHTML='<section class="hero"><h1>Collect the stars.</h1><p>Open exactly three cards. Duplicates increase your copy count.</p><div class="stats"><div class="stat"><b>'+total()+'</b><span class="small">Cards owned</span></div><div class="stat"><b>'+Object.keys(mine()).length+'</b><span class="small">Unique cards</span></div><div class="stat"><b>'+s.cards.length+'</b><span class="small">Catalog cards</span></div></div><button class="btn primary" '+(wait?'disabled':'')+' onclick="openPack()">'+button+'</button></section><section><h2>Card catalog</h2><div class="cards">'+s.cards.map(card).join('')+'</div></section>';if(wait)setTimeout(home,1000)}
function openPack(){if(cd())return;var a=s.cards.slice().sort(function(){return Math.random()-.5}).slice(0,3),c=mine();a.forEach(function(x){c[x.id]=(c[x.id]||0)+1});s.collection[s.user]=c;s.lastPack=Date.now();save();document.getElementById('main').innerHTML='<section class="hero"><h1>Pack opened!</h1><p>Three new cards added to your collection.</p><div class="cards">'+a.map(card).join('')+'</div><br><button class="btn" onclick="collection()">View collection</button></section>'}
function collection(){var a=Object.keys(mine()).map(function(id){return s.cards.find(function(c){return String(c.id)===id})}).filter(Boolean);document.getElementById('main').innerHTML='<section class="hero"><h1>My Collection</h1><p>'+a.length+' unique cards • '+total()+' total copies</p></section>'+(a.length?'<div class="cards">'+a.map(card).join('')+'</div>':'<div class="empty">No cards yet. Open your first pack.</div>')}
function leaderboard(){var a=Object.keys(s.users).map(function(u){var c=s.collection[u]||{};return {u:u,t:Object.values(c).reduce(function(x,y){return x+y},0),n:Object.keys(c).length}}).sort(function(x,y){return y.t-x.t});document.getElementById('main').innerHTML='<section class="hero"><h1>Leaderboard</h1><p>Local browser leaderboard for this simple static edition.</p></section><table class="table"><tr><th>#</th><th>Username</th><th>Total</th><th>Unique</th></tr>'+a.map(function(x,i){return '<tr><td>'+(i+1)+'</td><td>'+esc(x.u)+'</td><td>'+x.t+'</td><td>'+x.n+'</td></tr>'}).join('')+'</table>'}
function showCard(id){var c=s.cards.find(function(x){return x.id===id});if(!c)return;document.body.insertAdjacentHTML('beforeend','<div class="modal" id="modal" onclick="if(event.target.id===\'modal\')closeModal()"><div class="dialog"><button class="btn close" onclick="closeModal()">Close</button><div class="detail"><img src="'+esc(c.photo)+'"><div><div class="rarity">'+esc(c.rarity)+'</div><h1>'+esc(c.name)+'</h1><p class="muted">Age: '+c.age+'<br>Date of birth: '+esc(c.dob)+'</p><h3>Movies</h3><p>'+c.movies.map(esc).join(' • ')+'</p><p>'+esc(c.desc)+'</p><span class="pill">Owned ×'+(mine()[c.id]||0)+'</span></div></div></div></div>')}
function closeModal(){var x=document.getElementById('modal');if(x)x.remove()}
function admin(){if(s.user!=='6102000')return;document.getElementById('main').innerHTML='<section class="hero"><h1>Admin</h1><p>Create a new card for this browser catalog.</p></section><form class="form" onsubmit="event.preventDefault();addCard()"><input class="input" id="n" placeholder="Actress name" required><input class="input" id="ph" placeholder="Photo URL" required><input class="input" id="ag" type="number" placeholder="Age" required><input class="input" id="dob" placeholder="Date of birth" required><input class="input" id="mv" placeholder="Movie names, comma separated" required><select class="input" id="ra"><option>Common</option><option>Rare</option><option>Epic</option><option>Legendary</option></select><input class="input" id="de" placeholder="Description"><button class="btn primary">Create Card</button></form>'}
function addCard(){s.cards.push({id:Date.now(),name:document.getElementById('n').value,photo:document.getElementById('ph').value,age:Number(document.getElementById('ag').value),dob:document.getElementById('dob').value,movies:document.getElementById('mv').value.split(',').map(function(x){return x.trim()}).filter(Boolean),rarity:document.getElementById('ra').value,desc:document.getElementById('de').value||'Actress TCG card.'});save();alert('Card created.');admin()}
render();