const SUPABASE_URL='https://ewhoumxgaiigfcysrciw.supabase.co';
const SUPABASE_KEY='sb_publishable_AbWbVq8AJCGijBANXM6ESw_6mkATylt';
const db=window.supabase?.createClient(SUPABASE_URL,SUPABASE_KEY);
const SESSION_KEY='actress-tcg-session';
let session=null;
try{session=JSON.parse(localStorage.getItem(SESSION_KEY)||'null')}catch{localStorage.removeItem(SESSION_KEY)}
let cards=[];
let collection=[];
let leaderboardRows=[];
function esc(x){return String(x??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function setSession(x){session=x;localStorage.setItem(SESSION_KEY,JSON.stringify(x))}
function clearSession(){session=null;localStorage.removeItem(SESSION_KEY)}
function errorText(e){return e?.message||'Something went wrong.'}
function cd(){if(!session?.player?.last_pack_batch_at)return 0;return Math.max(0,3600000-(Date.now()-new Date(session.player.last_pack_batch_at).getTime()))}
function time(ms){let q=Math.ceil(ms/1000),h=Math.floor(q/3600),m=Math.floor(q%3600/60),s=q%60;return h?h+'h '+m+'m':m?m+'m '+s+'s':s+'s'}
async function loadCards(){if(!db)return;const {data,error}=await db.rpc('get_cards');if(!error)cards=data||[]}
async function loadCollection(){if(!session||!db)return false;const {data,error}=await db.rpc('get_collection',{p_player_id:session.player.id,p_session_token:session.token});if(error){if(/session expired/i.test(errorText(error))){clearSession();login();return false}return false}collection=data||[];return true}
async function loadLeaderboard(){if(!db)return;const {data,error}=await db.rpc('get_leaderboard');if(!error)leaderboardRows=data||[]}
function login(){document.getElementById('app').innerHTML='<div class="shell"><div class="login"><section class="hero"><div class="brand">ACTRESS <span>TCG</span></div><h1>Collect the stars.</h1><p>Open cards one by one, build your collection and inspect every card.</p></section><form class="form" onsubmit="event.preventDefault();enter()"><input class="input" id="u" placeholder="Username" required><input class="input" id="p" type="password" placeholder="Password" required><button class="btn primary">Enter TCG</button></form><div id="msg"></div></div></div>'}
async function enter(){if(!db){document.getElementById('msg').innerHTML='<div class="notice">Connection library failed to load. Please refresh the page.</div>';return}const u=document.getElementById('u').value.trim(),p=document.getElementById('p').value,box=document.getElementById('msg');box.innerHTML='<div class="notice">Connecting...</div>';let {data,error}=await db.rpc('login_player',{p_username:u,p_password:p});if(error||!data?.success){if(!data?.success&&u!=='6102000'){const r=await db.rpc('register_player',{p_username:u,p_password:p,p_display_name:u});if(!r.error&&r.data?.success)data=r.data;else{box.innerHTML='<div class="notice">'+esc(r.data?.error||errorText(error))+'</div>';return}}else{box.innerHTML='<div class="notice">'+esc(data?.error||errorText(error))+'</div>';return}}setSession(data);await start()}
async function start(){render();if(!session)return;if(!db){document.getElementById('main').innerHTML='<div class="notice">Connection library failed to load. Please refresh the page.</div>';return}try{await Promise.all([loadCards(),loadCollection()]);if(!session)return;home();if(session.player.role==='ADMIN')admin()}catch(e){console.error(e);document.getElementById('main').innerHTML='<div class="notice">Unable to connect to the game server. Please refresh and try again.</div>'}}
async function logout(){if(session?.token&&db)await db.rpc('logout_player',{p_token:session.token});clearSession();login()}
let pageRequest=0;let cooldownTimer=null;
function nav(){return '<header class="top"><div class="brand">ACTRESS <span>TCG</span></div><nav class="nav"><button class="btn" onclick="home()">Home</button><button class="btn" onclick="collectionPage()">Collection</button><button class="btn" onclick="leaderboardPage()">Leaderboard</button>'+(session.player.role==='ADMIN'?'<button class="btn primary" onclick="admin()">Create / Manage Cards</button>':'<button class="btn primary" onclick="createCardPage()">Create Card</button>')+'<button class="btn" onclick="session.player.role===&quot;ADMIN&quot;?adminFeedbackPage():feedbackPage()">Feedback</button>'+(session.player.role==='ADMIN'?'<button class="btn gold" onclick="admin()">Admin</button>':'')+'<button class="btn" onclick="logout()">Logout</button></nav></header>'}
function render(){if(!session){login();return}document.getElementById('app').innerHTML='<div class="shell">'+nav()+'<main id="main"></main><div class="footer">3 cards per pack • 1 hour cooldown • Supabase connected</div></div>';home()}
function formatDob(d){if(!d)return '—';const m=String(d).match(/^(\d{4})-(\d{2})-(\d{2})$/);return m?m[3]+'/'+m[2]+'/'+m[1]:String(d)}
function card(c,copies){return '<article class="card" onclick="showCard(\''+c.id+'\')"><img class="photo" src="'+esc(c.photo_url||'https://placehold.co/600x800/32121a/ffffff?text=Actress')+'" alt="'+esc(c.name)+'"><div class="cardbody"><div class="rarity">'+esc(c.rarity)+'</div><h3>'+esc(c.name)+'</h3><div class="small">Age '+(c.age??'—')+' • '+formatDob(c.date_of_birth)+'</div>'+(copies?'<span class="pill">Owned ×'+copies+'</span>':'')+'</div></article>'}
function total(){return collection.reduce((a,x)=>a+x.copies,0)}
function home(){const request=++pageRequest;if(cooldownTimer){clearTimeout(cooldownTimer);cooldownTimer=null}let wait=cd();document.getElementById('main').innerHTML='<section class="hero"><h1>Collect the stars.</h1><p>Open exactly three cards. They reveal one by one, then a one-hour cooldown starts.</p><div class="stats"><div class="stat"><b>'+total()+'</b><span class="small">Cards owned</span></div><div class="stat"><b>'+collection.length+'</b><span class="small">Unique cards</span></div><div class="stat"><b>'+cards.length+'</b><span class="small">Catalog cards</span></div></div><button class="btn primary" '+(wait?'disabled':'')+' onclick="openPack()">'+(wait?'Next pack in '+time(wait):'Open 3-card pack')+'</button></section><section><h2>Card catalog</h2><div class="cards">'+cards.slice(0,4).map(c=>card(c,collection.find(x=>x.card.id===c.id)?.copies||0)).join('')+'</div></section>';if(wait)cooldownTimer=setTimeout(()=>{if(request===pageRequest)home()},1000)}
async function openPack(){if(cd())return;const btn=document.querySelector('.hero .btn');if(btn)btn.disabled=true;const {data,error}=await db.rpc('open_pack',{p_player_id:session.player.id,p_pack_type:'STANDARD',p_session_token:session.token});if(error){if(/session expired/i.test(errorText(error))){clearSession();login();return}alert(errorText(error));if(btn)btn.disabled=false;return}session.player.last_pack_batch_at=new Date().toISOString();setSession(session);const got=data?.cards||[];await loadCollection();if(!got.length){home();return}document.getElementById('main').innerHTML='<section class="hero"><h1>Open cards one by one</h1><p>Reveal one card at a time. The one-hour cooldown has started.</p><div id="packCards" class="cards"></div><br><button class="btn primary" id="revealBtn" onclick="revealNextPackCard()">Reveal card</button></section>';window.packRevealCards=got;window.packRevealIndex=0}
function revealNextPackCard(){const got=window.packRevealCards||[];let index=window.packRevealIndex||0;if(index>=got.length)return;const wrap=document.getElementById('packCards');if(!wrap)return;wrap.insertAdjacentHTML('beforeend',card(got[index],collection.find(x=>x.card.id===got[index].id)?.copies||1));index++;window.packRevealIndex=index;const btn=document.getElementById('revealBtn');if(btn){if(index>=got.length){btn.textContent='View collection';btn.onclick=collectionPage}else btn.textContent='Reveal next card'}}
async function collectionPage(){const request=++pageRequest;if(!session)return;const ok=await loadCollection();if(request!==pageRequest||!ok||!session)return;const a=collection;document.getElementById('main').innerHTML='<section class="hero"><h1>My Collection</h1><p>'+a.length+' unique cards • '+total()+' total copies</p></section>'+(a.length?'<div class="cards">'+a.map(x=>card(x.card,x.copies)).join('')+'</div>':'<div class="empty">No cards yet. Open your first pack.</div>')}
async function createCardPage(){if(!session||session.player.role==='ADMIN')return;document.getElementById('main').innerHTML='<section class="hero"><h1>Create a Card</h1><p>Submit an actress card for admin review. Approved cards will appear in the catalog.</p></section><form class="form" onsubmit="event.preventDefault();submitCard()"><input class="input" id="sn" placeholder="Actress name" required><input class="input" id="sph" type="file" accept="image/*" required><input class="input" id="sag" type="number" placeholder="Age"><input class="input" id="sdob" type="date"><input class="input" id="smv" placeholder="Movie names, comma separated"><select class="input" id="sra"><option>Common</option><option>Rare</option><option>Epic</option><option>Legendary</option></select><input class="input" id="sde" placeholder="Description"><button class="btn primary">Submit Card</button></form><div id="submitMsg"></div>'}
async function submitCard(){const box=document.getElementById('submitMsg'),file=document.getElementById('sph')?.files[0];if(!file)return;box.innerHTML='<div class="notice">Submitting...</div>';const path=crypto.randomUUID()+'-'+file.name.replace(/[^a-zA-Z0-9._-]/g,'_');const up=await db.storage.from('card-photos').upload(path,file,{contentType:file.type,upsert:false});if(up.error){box.innerHTML='<div class="notice">'+esc(up.error.message)+'</div>';return}const url=db.storage.from('card-photos').getPublicUrl(path).data.publicUrl;const movies=document.getElementById('smv').value.split(',').map(x=>x.trim()).filter(Boolean);const r=await db.rpc('submit_card_submission',{p_player_id:session.player.id,p_session_token:session.token,p_name:document.getElementById('sn').value.trim(),p_age:Number(document.getElementById('sag').value)||null,p_dob:document.getElementById('sdob').value||null,p_movies:movies,p_photo_url:url,p_rarity:document.getElementById('sra').value,p_description:document.getElementById('sde').value.trim()||'Actress TCG card.'});if(r.error){box.innerHTML='<div class="notice">'+esc(errorText(r.error))+'</div>';return}box.innerHTML='<div class="notice">Card submitted for admin approval.</div>';document.getElementById('sn').value='';document.getElementById('sph').value='';document.getElementById('sag').value='';document.getElementById('sdob').value='';document.getElementById('smv').value='';document.getElementById('sde').value=''}
function feedbackPage(){const request=++pageRequest;if(!session)return;document.getElementById('main').innerHTML='<section class="hero"><h1>Feedback</h1><p>Send a message directly to the admin.</p></section><form class="form" onsubmit="event.preventDefault();sendFeedback()"><textarea class="input" id="feedbackMessage" maxlength="2000" rows="7" placeholder="Write your feedback..." required></textarea><button class="btn primary">Send feedback</button></form><div id="feedbackMsg"></div>'}
async function sendFeedback(){const box=document.getElementById('feedbackMsg'),message=document.getElementById('feedbackMessage')?.value.trim();if(!message)return;box.innerHTML='<div class="notice">Sending...</div>';const r=await db.rpc('submit_feedback',{p_player_id:session.player.id,p_session_token:session.token,p_message:message});if(r.error){if(/session expired/i.test(errorText(r.error))){clearSession();login();return}box.innerHTML='<div class="notice">'+esc(errorText(r.error))+'</div>';return}box.innerHTML='<div class="notice">Feedback sent to the admin.</div>';document.getElementById('feedbackMessage').value=''}
async function leaderboardPage(){const request=++pageRequest;await loadLeaderboard();if(request!==pageRequest||!session)return;document.getElementById('main').innerHTML='<section class="hero"><h1>Leaderboard</h1><p>Shared between all players through Supabase.</p></section><table class="table"><tr><th>#</th><th>Username</th><th>Total</th><th>Unique</th></tr>'+leaderboardRows.map((x,i)=>'<tr><td>'+(i+1)+'</td><td>'+esc(x.username)+'</td><td>'+x.total_cards+'</td><td>'+x.unique_cards+'</td></tr>').join('')+'</table>'}
function showCard(id){const c=cards.find(x=>x.id===id);if(!c)return;const own=collection.find(x=>x.card.id===id)?.copies||0;const movies=Array.isArray(c.movies)?c.movies:[];document.body.insertAdjacentHTML('beforeend','<div class="modal" id="modal" onclick="if(event.target.id===\'modal\')closeModal()"><div class="dialog"><button class="btn close" onclick="closeModal()">Close</button><div class="detail"><img src="'+esc(c.photo_url||'https://placehold.co/600x800')+'"><div><div class="rarity">'+esc(c.rarity)+'</div><h1>'+esc(c.name)+'</h1><p class="muted">Age: '+(c.age??'—')+'<br>Date of birth: '+esc(c.date_of_birth||'—')+'</p><h3>Movies</h3><p>'+movies.map(esc).join(' • ')+'</p><p>'+esc(c.description||'')+'</p><span class="pill">Owned ×'+own+'</span></div></div></div></div>')}
function closeModal(){document.getElementById('modal')?.remove()}
async function admin(){const request=++pageRequest;if(session.player.role!=='ADMIN')return;const [ur,cr,sr]=await Promise.all([db.rpc('admin_list_users',{p_session_token:session.token}),db.rpc('admin_list_cards',{p_session_token:session.token}),db.rpc('admin_list_card_submissions',{p_session_token:session.token})]);if(ur.error||cr.error||sr.error){alert(errorText(ur.error||cr.error||sr.error));return}if(request!==pageRequest||!session)return;const users=ur.data||[], acards=cr.data||[], submissions=sr.data||[];document.getElementById('main').innerHTML='<section class="hero"><h1>Admin</h1><p>Create cards, delete cards, and manage user accounts.</p></section><form class="form" onsubmit="event.preventDefault();addCard()"><input class="input" id="n" placeholder="Actress name" required><input class="input" id="ph" type="file" accept="image/*" required><input class="input" id="ag" type="number" placeholder="Age" required><input class="input" id="dob" type="date"><input class="input" id="mv" placeholder="Movie names, comma separated"><select class="input" id="ra"><option>Common</option><option>Rare</option><option>Epic</option><option>Legendary</option></select><input class="input" id="de" placeholder="Description"><button class="btn primary">Upload Photo & Create Card</button></form><section><h2>Cards</h2><div class="cards">'+acards.map(c=>'<article class="card"><img class="photo" src="'+esc(c.photo_url||'')+'" alt="'+esc(c.name)+'"><div class="cardbody"><div class="rarity">'+esc(c.rarity)+'</div><h3>'+esc(c.name)+'</h3><button class="btn" onclick="deleteCard(\''+c.id+'\')">Delete card</button></div></article>').join('')+'</div></section><section><h2>User Card Submissions</h2><div class="cards">'+(submissions.length?submissions.map(s=>'<article class="card"><img class="photo" src="'+esc(s.photo_url||'')+'" alt="'+esc(s.name)+'"><div class="cardbody"><div class="rarity">'+esc(s.rarity)+'</div><h3>'+esc(s.name)+'</h3><div class="small">Submitted by '+esc(s.username||'')+' • Age '+(s.age??'—')+' • '+formatDob(s.date_of_birth)+'</div><p>'+esc(s.description||'')+'</p><p>'+(Array.isArray(s.movies)?s.movies.map(esc).join(' • '):'')+'</p><button class="btn primary" onclick="approveSubmission(\''+s.id+'\')">Approve</button> <button class="btn" onclick="deleteSubmission(\''+s.id+'\')">Delete</button></div></article>').join(''):'<div class="empty">No pending card submissions.</div>')+'</div></section><section><h2>Users</h2><table class="table"><tr><th>Username</th><th>Role</th><th>Packs</th><th>Action</th></tr>'+users.map(u=>'<tr><td>'+esc(u.username)+'</td><td>'+esc(u.role)+'</td><td>'+u.total_packs_opened+'</td><td>'+(u.role==='ADMIN'?'Protected':'<button class="btn" onclick="deleteUser(\''+u.id+'\',\''+esc(u.username)+'\')">Delete user</button>')+'</td></tr>').join('')+'</table></section>'}
async function approveSubmission(id){if(!confirm('Approve this card and add it to the catalog?'))return;const r=await db.rpc('admin_approve_card_submission',{p_session_token:session.token,p_submission_id:id});if(r.error){alert(errorText(r.error));return}await loadCards();admin()}
async function deleteSubmission(id){if(!confirm('Delete this submitted card?'))return;const r=await db.rpc('admin_delete_card_submission',{p_session_token:session.token,p_submission_id:id});if(r.error){alert(errorText(r.error));return}admin()}
async function adminFeedbackPage(){const request=++pageRequest;if(!session||session.player.role!=='ADMIN')return;const r=await db.rpc('admin_list_feedback',{p_session_token:session.token});if(r.error){alert(errorText(r.error));return}if(request!==pageRequest||!session)return;const feedback=r.data||[];document.getElementById('main').innerHTML='<section class="hero"><h1>Feedback</h1><p>User messages sent to the admin.</p></section>'+(feedback.length?'<section><div class="table">'+feedback.map(f=>'<div class="notice"><b>'+esc(f.username)+'</b><div class="small">'+esc(new Date(f.created_at).toLocaleString())+'</div><p>'+esc(f.message)+'</p><button class="btn" data-feedback-id="'+esc(f.id)+'" onclick="deleteFeedback(this.dataset.feedbackId)">Delete</button></div>').join('')+'</div></section>':'<div class="empty">No feedback yet.</div>')}async function deleteFeedback(id){if(!confirm('Delete this feedback?'))return;const r=await db.rpc('admin_delete_feedback',{p_session_token:session.token,p_feedback_id:id});if(r.error){alert(errorText(r.error));return}adminFeedbackPage()}
async function deleteCard(id){if(!confirm('Delete this card? It will be removed from all collections.'))return;const request=++pageRequest;const r=await db.rpc('admin_delete_card',{p_session_token:session.token,p_card_id:id});if(r.error){alert(errorText(r.error));return}await loadCards();await loadCollection();if(request===pageRequest)admin()}
async function deleteUser(id,username){++pageRequest;if(!confirm('Delete user '+username+' and their collection?'))return;const r=await db.rpc('admin_delete_user',{p_session_token:session.token,p_player_id:id});if(r.error){alert(errorText(r.error));return}alert('User deleted.');admin()}
async function addCard(){const request=++pageRequest;const file=document.getElementById('ph').files[0];if(!file){alert('Choose a photo.');return}const path=crypto.randomUUID()+'-'+file.name.replace(/[^a-zA-Z0-9._-]/g,'_');const up=await db.storage.from('card-photos').upload(path,file,{contentType:file.type,upsert:false});if(up.error){alert(up.error.message);return}const url=db.storage.from('card-photos').getPublicUrl(path).data.publicUrl;const movies=document.getElementById('mv').value.split(',').map(x=>x.trim()).filter(Boolean);const r=await db.rpc('admin_create_card',{p_session_token:session.token,p_name:document.getElementById('n').value,p_age:Number(document.getElementById('ag').value)||null,p_dob:document.getElementById('dob').value||null,p_movies:movies,p_photo_url:url,p_rarity:document.getElementById('ra').value,p_description:document.getElementById('de').value||'Actress TCG card.'});if(r.error){alert(r.error.message);return}await loadCards();if(request===pageRequest){alert('Card created successfully.');admin()}}
start();